apiVersion: v2
name: argonix-crd
description: A Helm chart for the Argonix Kubernetes CRD controller
type: application
version: 0.1.1
appVersion: "0.1.1"
home: https://github.com/argonix-io/kubernetes-crd
sources:
  - https://github.com/argonix-io/kubernetes-crd
keywords:
  - argonix
  - monitoring
  - crd
  - operator
maintainers:
  - name: Argonix
    url: https://argonix.io
